name: Alternative Deploy to X-Server

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd fleeks-react
        npm ci
    
    - name: Build project
      run: |
        cd fleeks-react
        npm run build
    
    - name: Install lftp
      run: sudo apt-get install -y lftp
    
    - name: Deploy via LFTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "
        set ftp:ssl-allow no
        set ftp:passive-mode yes
        open ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER
        mirror --reverse --delete --verbose \
          --exclude .git/ \
          --exclude .github/ \
          --exclude node_modules/ \
          --exclude fleeks-react/src/ \
          --exclude fleeks-react/node_modules/ \
          --exclude .gitignore \
          --exclude '*.md' \
          ./ ./public_html/
        bye
        "